name: Instalar HIKARI

on:
  push:
    paths:
      - "HIKARI-Cloudinary-Pronto.zip"

permissions:
  contents: write

jobs:
  instalar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Descompactar HIKARI
        run: |
          unzip -o HIKARI-Cloudinary-Pronto.zip -d .
          rm HIKARI-Cloudinary-Pronto.zip

      - name: Salvar arquivos
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Instalar HIKARI Cloudinary"
          git push
